### ISSUE TITLE
Please, tag your releases

### ISSUE THREAD

**Issue by paulodiovani** [z24/tty2gif#3]
`v0.2` requires libmagick >= 6.8.6-4 due to addition of `optimizeImageLayers()` function.

This version is not yet avaiable on Ubuntu 14.04, so I have to rollback to `v0.1` to be able to compile.

Would be better to have tags and a releases pages on github, including dependency info.

**Comment by codyzu** [comment]
I ran into the same issue with Ubuntu 14.04 and the only solution I found was using the v0.1 tag as @paulodiovani noted.

It would be nice to add this specific note in the readme for Ubuntu 14.04 users. I stumbled upon this issue while googling the issue, so to make it more clear could be helpful. I can do this if you want.
